"""Chat router — POST /api/chat

Accepts a natural-language question about the user's transaction data and
returns a RAG-grounded response generated by the LLM.
"""

import logging

from fastapi import APIRouter, HTTPException, Request

try:
    from models.schemas import ChatRequest, ChatResponse
    from services import llm_structurer
    from services.llm_structurer import GroqAPIError
    from services.rag_engine import query_and_respond
except ImportError:
    from backend.models.schemas import ChatRequest, ChatResponse
    from backend.services import llm_structurer
    from backend.services.llm_structurer import GroqAPIError
    from backend.services.rag_engine import query_and_respond

logger = logging.getLogger(__name__)

router = APIRouter()


@router.post("/chat", response_model=ChatResponse)
async def chat(chat_request: ChatRequest, request: Request):
    """Answer a question about the user's transactions using RAG.

    The message field is validated by Pydantic (1–500 characters).
    Header X-Groq-API-Key (optional): User-provided Groq API key for this request.
    Returns 429 on Groq rate limit exhaustion and 500 on unexpected errors.
    """
    # Extract user-provided API key if present
    user_api_key = request.headers.get("X-Groq-API-Key")
    if user_api_key:
        llm_structurer.set_user_api_key(user_api_key)
    
    try:
        answer = query_and_respond(chat_request.message)
    except GroqAPIError as exc:
        if "Rate limit" in str(exc):
            raise HTTPException(
                status_code=429,
                detail="Rate limit reached. Please try again in a few minutes.",
            )
        raise HTTPException(status_code=500, detail=str(exc))
    except Exception as exc:
        logger.exception("Unexpected error in chat endpoint: %s", exc)
        raise HTTPException(status_code=500, detail="An unexpected error occurred.")
    finally:
        # Clear user API key after request completes
        if user_api_key:
            llm_structurer.set_user_api_key(None)

    return ChatResponse(response=answer)
